name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - run: npm install
        working-directory: ./webui

      - run: npm run build
        working-directory: ./webui

      - run: rustup override set 1.86.0

      - run: cargo build --verbose

      - run: cargo test --verbose
