name: Release Docker

on:
  push:
    branches: ["release"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "VERSION=$(sed -n 's/version = "\(.*\)"$/\1/p' Cargo.toml)" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag vvlookman/aiter:${{ env.VERSION }} \
            --push \
            .
